#include <catch2/catch_test_macros.hpp>

#include <cstdint>
#include "car.h"
#include <random_provider.h>


TEST_CASE( "CCar instance", "[CCar]" ) {
    CRandomProvider random_provider(0);
    CCar car(random_provider);

    REQUIRE( car.getGenes() == "XFDFHKGRPQMSRHTCIMDOKLPMGUUAFRPABXFTGWMSCDVDNOFLMMFXFHJUMYZOTFIKVTXWSQVDWGAZEOTBMMACGSPPEYWOWUWUIZTLXWFCEQDXAAKORXMSERDMGZVCIUDQLMJIOJWLCXCMWOHLALBOAHWFZQFPGPXJVLXENZRQNSMRRIORYTWZBEBAPOGXHCEOJZJKMFUNLCWXXPVDDWYKLRODMPLQIOKSFUYYQFNUFHXTJOJVBUOADIEDAOGWGWRFSTPNTSFUXNGDTXHSQEVIVFOJOGZAKQHIYKTTWKSXTGYA" );
}
