@startuml
interface IModalDialog
interface IGrCar
interface IPanel
interface ICar
interface ICarFactory
interface IWorld
interface IGaCar
interface IGaBox2dView
interface IGaBox2dDoc
interface IPhysCar
class ga_params_t
class CPoint
class GaStatus
class CEnv
class vec2f_t
class TFracao
class CBilinearAmostras
class CLinearMap
class doublex
class CCarDef
class gr_circle_t
class CIdInfoDlg
class CMainMenu
class CAngulo
class CCronometro
class BasicModalDlg
class CRodaParams
class CGrCar
class GaStatusSerializer
class CSolidBrush
class CEditorChaoDlg
class CPen
class CGaInfoDlg
class CThreadParams
class CGaInfo
class CCarFactory
class CRandom
class GaServer
class CGaBox2dApp
class CGaCar
class CWndPreviewChao
class CGaParamsDlg
class CGaBox2dDoc
class CGa
class CWorld
class CPhysCar
class CCar
class CGaBox2dView
CGaBox2dView -down-|> "IGaBox2dView"
CGaBox2dView -down-> "CGaInfoDlg"
CGaBox2dView -down-> "socket>"
CGaBox2dView -down-> "vector<char>"
CGaBox2dView -down-> "GaStatusSerializer"
CGaBox2dView -down-> "io_context>"
CGaBox2dView -down-> "CIdInfoDlg"
CGaBox2dView -down-> "CGaInfo"
CGaBox2dView -down-> "IGaBox2dDoc"
CGaBox2dView -down-> "CGaParamsDlg"
CGaBox2dView -down-> "CThreadParams"
CGaBox2dView ..> "GaStatus"
CGaBox2dView ..> "CEnv"
CGaBox2dView ..> "RenderWindow"
CGaBox2dView ..> "ga_params_t"
CGa -down-> "ICarFactory"
CGa -down-> "ICar"
CGa -down-> "discrete_distribution<size_t>"
CGa -down-> "string>"
CGa ..> "IWorld"
CWorld -down-|> "IWorld"
CWorld -down-> "b2BodyId"
CWorld -down-> "b2WorldId"
CWorld -down-> "b2ChainId"
CWorld ..> "CEnv"
CPhysCar -down-|> "IPhysCar"
CPhysCar -down-> "IWorld"
CPhysCar ..> "IGrCar"
CPhysCar ..> "CCarDef"
CPhysCar ..> "fitness_params_t"
CCar -down-|> "ICar"
CCar -down-> "IGaCar"
CCar -down-> "IPhysCar"
CCar -down-> "IGrCar"
CCar ..> "IWorld"
CWndPreviewChao -down-> "CEnv"
CWndPreviewChao -down-> "RenderWindow"
CWndPreviewChao -down-> "b2Vec2"
CWndPreviewChao -down-> "CPoint"
IPhysCar ..> "IGrCar"
IPhysCar ..> "CCarDef"
IPhysCar ..> "IWorld"
IPhysCar ..> "fitness_params_t"
CGaParamsDlg -down-|> "BasicModalDlg"
CGaParamsDlg -down-|> "ga_params_t"
CGaParamsDlg -down-> "using"
CGaParamsDlg -down-> "callback_t"
CGaBox2dDoc -down-|> "IGaBox2dDoc"
CGaBox2dDoc -down-> "CEnv"
CGaBox2dDoc -down-> "ICar"
CGaBox2dDoc -down-> "IWorld"
GaServer -down-> "vec_socket_t"
GaServer -down-> "using"
GaServer ..> "GaStatus"
IGaBox2dView ..> "IGaBox2dDoc"
IGaBox2dView ..> "ga_params_t"
IGaBox2dView ..> "GaStatus"
IGaBox2dDoc ..> "CEnv"
IGaBox2dDoc ..> "ICar"
IGaBox2dDoc ..> "IWorld"
CGaBox2dApp -down-> "CMainMenu"
CGaBox2dApp -down-> "IGaBox2dDoc"
CGaBox2dApp -down-> "IGaBox2dView"
CGaCar -down-|> "IGaCar"
CGaCar -down-> "CCarDef"
CGaCar ..> "fitness_params_t"
CRodaParams -down-> "body_params_t"
CRodaParams -down-> "circle_params_t"
CGrCar -down-|> "IGrCar"
CGrCar -down-> "gr_circle_t"
GaStatusSerializer -down-> "static  string"
GaStatusSerializer ..> "GaStatus"
CSolidBrush -down-> "Color"
CSolidBrush ..> "Shape"
CEditorChaoDlg -down-> "CEnv"
CEditorChaoDlg -down-> "CWndPreviewChao"
IGaCar ..> "fitness_params_t"
IGaCar ..> "CCarDef"
CPen -down-> "Color"
CPen ..> "Shape"
CGaInfoDlg -down-|> "IPanel"
CGaInfoDlg ..> "GaStatus"
CThreadParams -down-> "CEnv"
CThreadParams -down-> "ga_params_t"
CGaInfo -down-> "CEnv"
CGaInfo -down-> "ICar"
CCarFactory -down-|> "ICarFactory"
CCarFactory ..> "ICar"
CRandom -down-> "mt19937"
CRandom ..> "T"
CCarDef -down-> "CRodaParams"
gr_circle_t -down-> "Vector2f"
CIdInfoDlg -down-|> "IPanel"
CMainMenu -down-> "IGaBox2dView"
ICar ..> "IWorld"
ICarFactory ..> "ICar"
CAngulo -down-> "doublex"
CCronometro -down-> "system_clock>"
BasicModalDlg -down-|> "IModalDialog"
IWorld ..> "CEnv"
@enduml
