@startuml
interface IGrCar
interface ICar
interface ICarFactory
interface IWorld
interface IGaBox2dView
interface IGaCar
interface IGaBox2dDoc
interface IPhysCar
class ga_params_t
class CPoint
class CIdInfoDlg
class CEnv
class vec2f_t
class TFracao
class CBilinearAmostras
class CLinearMap
class doublex
class CCarDef
class gr_circle_t
class CAngulo
class CCronometro
class CRodaParams
class CGrCar
class CSolidBrush
class CEditorChaoDlg
class CPen
class CGaInfoDlg
class CThreadParams
class CGaInfo
class CCarFactory
class CGaParamsDlg
class CRandom
class CGa
class CGaBox2dApp
class CGaCar
class CWndPreviewChao
class CMainMenu
class CGaBox2dDoc
class CWorld
class CPhysCar
class CCar
class CGaBox2dView
CGaBox2dView -down-|> "IGaBox2dView"
CGaBox2dView -down-|> "enable_shared_from_this<CGaBox2dView>"
CGaBox2dView -down-> "thread"
CGaBox2dView -down-> "IGaBox2dDoc"
CGaBox2dView -down-> "CGaInfo"
CGaBox2dView -down-> "CThreadParams"
CGaBox2dView ..> "CEnv"
CGaBox2dView ..> "ga_params_t"
CGaBox2dView ..> "RenderWindow"
CWorld -down-|> "IWorld"
CWorld -down-> "b2BodyId"
CWorld -down-> "b2ChainId"
CWorld -down-> "b2WorldId"
CWorld ..> "CEnv"
CPhysCar -down-|> "IPhysCar"
CPhysCar -down-> "IWorld"
CPhysCar ..> "IGrCar"
CPhysCar ..> "CCarDef"
CPhysCar ..> "fitness_params_t"
CCar -down-|> "ICar"
CCar -down-> "IGaCar"
CCar -down-> "IPhysCar"
CCar -down-> "IGrCar"
CCar ..> "IWorld"
CWndPreviewChao -down-> "b2Vec2"
CWndPreviewChao -down-> "CPoint"
CWndPreviewChao -down-> "CEnv"
CWndPreviewChao -down-> "RenderWindow"
CMainMenu -down-> "IGaBox2dView"
CMainMenu ..> "CEditorChaoDlg"
CMainMenu ..> "CGaInfoDlg"
CMainMenu ..> "CGaParamsDlg"
IPhysCar ..> "IGrCar"
IPhysCar ..> "CCarDef"
IPhysCar ..> "fitness_params_t"
IPhysCar ..> "IWorld"
CGaBox2dDoc -down-|> "IGaBox2dDoc"
CGaBox2dDoc -down-> "ICar"
CGaBox2dDoc -down-> "IWorld"
CGaBox2dDoc -down-> "CEnv"
CGa -down-> "ICar"
CGa -down-> "ICarFactory"
CGa ..> "IWorld"
IGaBox2dDoc ..> "ICar"
IGaBox2dDoc ..> "IWorld"
IGaBox2dDoc ..> "CEnv"
CGaBox2dApp -down-> "IGaBox2dView"
CGaBox2dApp -down-> "IGaBox2dDoc"
CGaBox2dApp -down-> "CMainMenu"
CGaCar -down-|> "IGaCar"
CGaCar -down-> "CCarDef"
CGaCar ..> "fitness_params_t"
CRodaParams -down-> "body_params_t"
CRodaParams -down-> "circle_params_t"
IGaBox2dView ..> "IGaBox2dDoc"
IGaBox2dView ..> "ga_params_t"
CGrCar -down-|> "IGrCar"
CGrCar -down-> "gr_circle_t"
CSolidBrush -down-> "Color"
CSolidBrush ..> "Shape"
CEditorChaoDlg -down-> "CWndPreviewChao"
CEditorChaoDlg -down-> "CEnv"
IGaCar ..> "fitness_params_t"
IGaCar ..> "CCarDef"
CPen -down-> "Color"
CPen ..> "Shape"
CGaInfoDlg -down-> "IGaBox2dView"
CGaInfoDlg ..> "CGaInfo"
CThreadParams -down-> "CEnv"
CThreadParams -down-> "ga_params_t"
CGaInfo -down-> "ICar"
CGaInfo -down-> "CEnv"
CCarFactory -down-|> "ICarFactory"
CCarFactory ..> "ICar"
CGaParamsDlg -down-> "IGaBox2dView"
CGaParamsDlg -down-> "ga_params_t"
CRandom -down-> "mt19937"
CRandom ..> "T"
CCarDef -down-> "CRodaParams"
gr_circle_t -down-> "Vector2f"
ICar ..> "IWorld"
ICarFactory ..> "ICar"
CAngulo -down-> "doublex"
CCronometro -down-> "system_clock>"
IWorld ..> "CEnv"
@enduml
